const cardImages = [
    [   
        require('../assets/cards/2C.png'),
        require('../assets/cards/3C.png'),
        require('../assets/cards/4C.png'),
        require('../assets/cards/5C.png'),
        require('../assets/cards/6C.png'),
        require('../assets/cards/7C.png'),
        require('../assets/cards/8C.png'),
        require('../assets/cards/9C.png'),
        require('../assets/cards/10C.png'),
        require('../assets/cards/JC.png'),
        require('../assets/cards/QC.png'),
        require('../assets/cards/KC.png'),
        require('../assets/cards/AC.png')
    ],
    [   
        require('../assets/cards/2D.png'),
        require('../assets/cards/3D.png'),
        require('../assets/cards/4D.png'),
        require('../assets/cards/5D.png'),
        require('../assets/cards/6D.png'),
        require('../assets/cards/7D.png'),
        require('../assets/cards/8D.png'),
        require('../assets/cards/9D.png'),
        require('../assets/cards/10D.png'),
        require('../assets/cards/JD.png'),
        require('../assets/cards/QD.png'),
        require('../assets/cards/KD.png'),
        require('../assets/cards/AD.png')
    ],
    [   
        require('../assets/cards/2S.png'),
        require('../assets/cards/3S.png'),
        require('../assets/cards/4S.png'),
        require('../assets/cards/5S.png'),
        require('../assets/cards/6S.png'),
        require('../assets/cards/7S.png'),
        require('../assets/cards/8S.png'),
        require('../assets/cards/9S.png'),
        require('../assets/cards/10S.png'),
        require('../assets/cards/JS.png'),
        require('../assets/cards/QS.png'),
        require('../assets/cards/KS.png'),
        require('../assets/cards/AS.png')
    ],
    [   
        require('../assets/cards/2H.png'),
        require('../assets/cards/3H.png'),
        require('../assets/cards/4H.png'),
        require('../assets/cards/5H.png'),
        require('../assets/cards/6H.png'),
        require('../assets/cards/7H.png'),
        require('../assets/cards/8H.png'),
        require('../assets/cards/9H.png'),
        require('../assets/cards/10H.png'),
        require('../assets/cards/JH.png'),
        require('../assets/cards/QH.png'),
        require('../assets/cards/KH.png'),
        require('../assets/cards/AH.png')
    ]
]

export default cardImages;